### ISSUE TITLE
Append rather than replace context fields

### ISSUE THREAD

**Issue by jszwedko** [bloom42/rz-go#1]
Is it possible to append context fields rather than replace them as `With` does? I'm struggling to find a way.

My use case is preserving the context of the "root" logger when creating a sublogger, but adding additional context to be carried forward.

Kudos on a great library! I appreciate the thought put into the interface.

**Comment by z0mbie42** [comment]
Hi, currently not. I will add it in the next 24 hours. Do you have an idea about how to call this method ? 

`logger.UpdateContext` ?

(There is currently a private method `logger.updateContext` method used for the`HTTPHandler` which do exactly what you describe)

**Comment by jszwedko** [comment]
:+1: given that the current method is just called `rz.With`, perhaps `rz.Append`?

An alternative, would be provide a method for grabbing the current context (e.g. `logger.Fields`) that returns a `map[string]interface{}` that could be passed to `e.Fields` so you'd end up with something like:

```
logger.Config(rz.With(func(e *rz.Event) {
  e.String("new", "field").
  Fields(logger.Fields())
}))
```

Thanks for your attention!

**Comment by z0mbie42** [comment]
The problem with the second solution is that it's highly inefficient and does not fit the `HTTPHandler` case.

The problem with the first one is that it's not thread safe, but it fits the `HTTPHandler` case and most of the others.

According to some benchmarks (https://gist.github.com/TheHippo/75babf83556dc6f638a4) adding a mutex in `Append` to become thread safe seems not include too much overhead  because this type of operation should not be in the hot path.

So I think `Append` is our champion here.

I will add it as soon as I'm in front of my computer :)

**Comment by z0mbie42** [comment]
8ec91a292b0e7261efb4a984c09f3b26cc3996b5 must do the be good.

**Comment by jszwedko** [comment]
@z0mbie42 looks great! Tested it just now to verify it meets my use-case.

Thanks again!
